-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TIPO_USUARIO` (
  `ID_TIPO_USUARIO` INT NOT NULL,
  `DESCRICAO_TIPO_USUARIO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TIPO_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `ID_USUARIO` INT NOT NULL,
  `NOME_USER` VARCHAR(100) NOT NULL,
  `EMAIL_USER` VARCHAR(45) NOT NULL,
  `TELEFONE_USER` INT NOT NULL,
  `SENHA_USER` VARCHAR(45) NOT NULL,
  `TIPO_USUARIO_ID_TIPO_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_USUARIO`, `TIPO_USUARIO_ID_TIPO_USUARIO`),
  CONSTRAINT `fk_USUARIO_TIPO_USUARIO1`
    FOREIGN KEY (`TIPO_USUARIO_ID_TIPO_USUARIO`)
    REFERENCES `TIPO_USUARIO` (`ID_TIPO_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOCAL` (
  `ID_LOCAL` INT NOT NULL,
  `ESTABELECIMENTO_LOCAL` VARCHAR(90) NOT NULL,
  `LOGRADOURO_LOCAL` VARCHAR(100) NOT NULL,
  `TELEFONE_LOCAL` VARCHAR(45) NOT NULL,
  `CEP_LOCAL` VARCHAR(45) NOT NULL,
  `BAIRRO_LOCAL` VARCHAR(45) NOT NULL,
  `UF_LOCAL` VARCHAR(45) NOT NULL,
  `DESCRICAO_LOCAL` VARCHAR(45) NOT NULL,
  `CIDADE_LOCAL` VARCHAR(45) NOT NULL,
  `RUA_LOCAL` VARCHAR(45) NOT NULL,
  `HORARIO_ABERTURA` TIME NOT NULL,
  `HORARIO_FECHAMENTO` TIME NOT NULL,
  `USUARIO_ID_USUARIO` INT NOT NULL,
  `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_LOCAL`, `USUARIO_ID_USUARIO`, `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO`),
  CONSTRAINT `fk_LOCAL_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO` , `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO`)
    REFERENCES `USUARIO` (`ID_USUARIO` , `TIPO_USUARIO_ID_TIPO_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TIPO_LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TIPO_LOCAL` (
  `ID_TIPO_LOCAL` INT NOT NULL,
  `DESCRICAO_TIPO_LOCAL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_LOCAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AVALIACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AVALIACAO` (
  `ID_AVALIACAO` INT NOT NULL,
  `COMENTARIO` VARCHAR(45) NULL,
  `STAR` INT NULL,
  `USUARIO_ID_USUARIO` INT NOT NULL,
  `LOCAL_ID_LOCAL` INT NOT NULL,
  PRIMARY KEY (`ID_AVALIACAO`, `USUARIO_ID_USUARIO`, `LOCAL_ID_LOCAL`),
  CONSTRAINT `fk_AVALIACAO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AVALIACAO_LOCAL1`
    FOREIGN KEY (`LOCAL_ID_LOCAL`)
    REFERENCES `LOCAL` (`ID_LOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `LOCAL_has_TIPO_LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LOCAL_has_TIPO_LOCAL` (
  `LOCAL_ID_LOCAL` INT NOT NULL,
  `LOCAL_AVALIACAO_ID_AVALIACAO` INT NOT NULL,
  `TIPO_LOCAL_ID_TIPO_LOCAL` INT NOT NULL,
  PRIMARY KEY (`LOCAL_ID_LOCAL`, `LOCAL_AVALIACAO_ID_AVALIACAO`, `TIPO_LOCAL_ID_TIPO_LOCAL`),
  CONSTRAINT `fk_LOCAL_has_TIPO_LOCAL_LOCAL`
    FOREIGN KEY (`LOCAL_ID_LOCAL`)
    REFERENCES `LOCAL` (`ID_LOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCAL_has_TIPO_LOCAL_TIPO_LOCAL1`
    FOREIGN KEY (`TIPO_LOCAL_ID_TIPO_LOCAL`)
    REFERENCES `TIPO_LOCAL` (`ID_TIPO_LOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
