-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`TIPO_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_USUARIO` (
  `ID_TIPO_USUARIO` INT NOT NULL,
  `DESCRICAO_TIPO_USUARIO` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_TIPO_USUARIO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `ID_USUARIO` INT NOT NULL,
  `NOME_USER` VARCHAR(100) NOT NULL,
  `EMAIL_USER` VARCHAR(45) NOT NULL,
  `TELEFONE_USER` INT NOT NULL,
  `SENHA_USER` VARCHAR(45) NOT NULL,
  `TIPO_USUARIO_ID_TIPO_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_USUARIO`, `TIPO_USUARIO_ID_TIPO_USUARIO`),
  INDEX `fk_USUARIO_TIPO_USUARIO1_idx` (`TIPO_USUARIO_ID_TIPO_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_TIPO_USUARIO1`
    FOREIGN KEY (`TIPO_USUARIO_ID_TIPO_USUARIO`)
    REFERENCES `mydb`.`TIPO_USUARIO` (`ID_TIPO_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOCAL` (
  `ID_LOCAL` INT NOT NULL,
  `NOME_LOCAL` VARCHAR(90) NOT NULL,
  `LOCALIZACAO_LOCAL` VARCHAR(45) NOT NULL,
  `TELEFONE_LOCAL` VARCHAR(45) NOT NULL,
  `CEP_LOCAL` VARCHAR(45) NOT NULL,
  `BAIRRO_LOCAL` VARCHAR(45) NOT NULL,
  `RUA_LOCAL` VARCHAR(45) NOT NULL,
  `USUARIO_ID_USUARIO` INT NOT NULL,
  `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO` INT NOT NULL,
  PRIMARY KEY (`ID_LOCAL`, `USUARIO_ID_USUARIO`, `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO`),
  INDEX `fk_LOCAL_USUARIO1_idx` (`USUARIO_ID_USUARIO` ASC, `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO` ASC) VISIBLE,
  CONSTRAINT `fk_LOCAL_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO` , `USUARIO_TIPO_USUARIO_ID_TIPO_USUARIO`)
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO` , `TIPO_USUARIO_ID_TIPO_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TIPO_LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TIPO_LOCAL` (
  `ID_TIPO_LOCAL` INT NOT NULL,
  `DESCRICAO_TIPO_LOCAL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_TIPO_LOCAL`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`AVALIACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`AVALIACAO` (
  `ID_AVALIACAO` INT NOT NULL,
  `COMENTARIO` VARCHAR(45) NULL,
  `STAR` INT NULL,
  `USUARIO_ID_USUARIO` INT NOT NULL,
  `LOCAL_ID_LOCAL` INT NOT NULL,
  PRIMARY KEY (`ID_AVALIACAO`, `USUARIO_ID_USUARIO`, `LOCAL_ID_LOCAL`),
  INDEX `fk_AVALIACAO_USUARIO1_idx` (`USUARIO_ID_USUARIO` ASC) VISIBLE,
  INDEX `fk_AVALIACAO_LOCAL1_idx` (`LOCAL_ID_LOCAL` ASC) VISIBLE,
  CONSTRAINT `fk_AVALIACAO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID_USUARIO`)
    REFERENCES `mydb`.`USUARIO` (`ID_USUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AVALIACAO_LOCAL1`
    FOREIGN KEY (`LOCAL_ID_LOCAL`)
    REFERENCES `mydb`.`LOCAL` (`ID_LOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOCAL_has_TIPO_LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOCAL_has_TIPO_LOCAL` (
  `LOCAL_ID_LOCAL` INT NOT NULL,
  `LOCAL_AVALIACAO_ID_AVALIACAO` INT NOT NULL,
  `TIPO_LOCAL_ID_TIPO_LOCAL` INT NOT NULL,
  PRIMARY KEY (`LOCAL_ID_LOCAL`, `LOCAL_AVALIACAO_ID_AVALIACAO`, `TIPO_LOCAL_ID_TIPO_LOCAL`),
  INDEX `fk_LOCAL_has_TIPO_LOCAL_TIPO_LOCAL1_idx` (`TIPO_LOCAL_ID_TIPO_LOCAL` ASC) VISIBLE,
  INDEX `fk_LOCAL_has_TIPO_LOCAL_LOCAL_idx` (`LOCAL_ID_LOCAL` ASC, `LOCAL_AVALIACAO_ID_AVALIACAO` ASC) VISIBLE,
  CONSTRAINT `fk_LOCAL_has_TIPO_LOCAL_LOCAL`
    FOREIGN KEY (`LOCAL_ID_LOCAL`)
    REFERENCES `mydb`.`LOCAL` (`ID_LOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCAL_has_TIPO_LOCAL_TIPO_LOCAL1`
    FOREIGN KEY (`TIPO_LOCAL_ID_TIPO_LOCAL`)
    REFERENCES `mydb`.`TIPO_LOCAL` (`ID_TIPO_LOCAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
