-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `RESTAURANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESTAURANTE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `DESCRICAO` VARCHAR(255) NULL,
  `CEP` VARCHAR(9) NOT NULL,
  `LOGRADOURO` VARCHAR(90) NOT NULL,
  `BAIRRO` VARCHAR(50) NOT NULL,
  `NUMERO` INT NOT NULL,
  `HORARIO` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FOTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOTO` (
  `ID` INT NOT NULL,
  `URL` VARCHAR(100) NULL,
  `RESTAURANTE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_FOTO_RESTAURANTE1_idx` (`RESTAURANTE_ID` ASC),
  CONSTRAINT `fk_FOTO_RESTAURANTE1`
    FOREIGN KEY (`RESTAURANTE_ID`)
    REFERENCES `RESTAURANTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TELEFONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TELEFONE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `TELEFONE` INT NOT NULL,
  `RESTAURANTE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TELEFONE_RESTAURANTE_idx` (`RESTAURANTE_ID` ASC),
  CONSTRAINT `fk_TELEFONE_RESTAURANTE`
    FOREIGN KEY (`RESTAURANTE_ID`)
    REFERENCES `RESTAURANTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOCIAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOCIAL` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(100) NULL,
  `RESTAURANTE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_SOCIAL_RESTAURANTE1_idx` (`RESTAURANTE_ID` ASC),
  CONSTRAINT `fk_SOCIAL_RESTAURANTE1`
    FOREIGN KEY (`RESTAURANTE_ID`)
    REFERENCES `RESTAURANTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CATEGORIA` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CATEGORIA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESTAURANTE_has_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESTAURANTE_has_CATEGORIA` (
  `RESTAURANTE_ID` INT NOT NULL,
  `CATEGORIA_ID` INT NOT NULL,
  PRIMARY KEY (`RESTAURANTE_ID`, `CATEGORIA_ID`),
  INDEX `fk_RESTAURANTE_has_CATEGORIA_CATEGORIA1_idx` (`CATEGORIA_ID` ASC),
  INDEX `fk_RESTAURANTE_has_CATEGORIA_RESTAURANTE1_idx` (`RESTAURANTE_ID` ASC),
  CONSTRAINT `fk_RESTAURANTE_has_CATEGORIA_RESTAURANTE1`
    FOREIGN KEY (`RESTAURANTE_ID`)
    REFERENCES `RESTAURANTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESTAURANTE_has_CATEGORIA_CATEGORIA1`
    FOREIGN KEY (`CATEGORIA_ID`)
    REFERENCES `CATEGORIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TIPOUSUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TIPOUSUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(100) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `TIPOUSUARIO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `TIPOUSUARIO_ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
  INDEX `fk_USUARIO_TIPOUSUARIO1_idx` (`TIPOUSUARIO_ID` ASC),
  CONSTRAINT `fk_USUARIO_TIPOUSUARIO1`
    FOREIGN KEY (`TIPOUSUARIO_ID`)
    REFERENCES `TIPOUSUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AVALIACAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AVALIACAO` (
  `USUARIO_ID` INT NOT NULL,
  `USUARIO_TIPOUSUARIO_ID` INT NOT NULL,
  `RESTAURANTE_ID` INT NOT NULL,
  `ID` VARCHAR(45) NOT NULL,
  `ESTRELAS` INT NULL,
  `COMENTARIO` VARCHAR(255) NULL,
  PRIMARY KEY (`USUARIO_ID`, `USUARIO_TIPOUSUARIO_ID`, `RESTAURANTE_ID`, `ID`),
  INDEX `fk_USUARIO_has_RESTAURANTE_RESTAURANTE1_idx` (`RESTAURANTE_ID` ASC),
  INDEX `fk_USUARIO_has_RESTAURANTE_USUARIO1_idx` (`USUARIO_ID` ASC, `USUARIO_TIPOUSUARIO_ID` ASC),
  CONSTRAINT `fk_USUARIO_has_RESTAURANTE_USUARIO1`
    FOREIGN KEY (`USUARIO_ID` , `USUARIO_TIPOUSUARIO_ID`)
    REFERENCES `USUARIO` (`ID` , `TIPOUSUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIO_has_RESTAURANTE_RESTAURANTE1`
    FOREIGN KEY (`RESTAURANTE_ID`)
    REFERENCES `RESTAURANTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
